
path:
    project_path: /root/repo
    data_path: /root/data
    train_csv_path: /root/data/CheXpert-v1.0-small/train.csv
    test_csv_path: /root/data/CheXpert-v1.0-small/valid.csv


model: &model 
  name: densenet121
  model_params: &model_params
      classes: 5

image:
    image_fix_length: 320
    progressive_image_size: 160

train_mode: default

train_params:
    loss:
        balanceBCE:
            beta: 0.99
    epoch:  20
    log_interval: 10
    batch_size: 64
    early_stopping: True
      patient: 3

    
progressive_train_params:
   
    loss:
        balanceBCE:
            beta: 0.99
    epoch:  20
    log_interval: 10
    batch_size: 64
    early_stopping: True
      patient: 3
  
mini_data:
    train: 200
    test: 200

progressive_mini_data:
  train: 200
  val : 200


    


