
path:
    project_path: /root/repo
    data_path: /root/data
    process_train: /root/data/CheXpert-v1.0-small/k_fold.csv
    process_test: /root/data/CheXpert-v1.0-small/valid_process.csv
model: &model 
    name: densenet121
    model_params: &model_params
        classes: 5
image:
    image_fix_length: 320
    progressive_image_size: 160
train_mode: default

epoch: &epoch 10

frontal_epoch: 1
train_params:
    class_idx: 7,10,11,13,15
    loss:
        balanceBCE:
            beta: 0.99
    
    log_interval: 10
    batch_size: 32
    early_stopping: True
    patient: 3  

optimizer: 
    name: Adam
    optimizer_params:
        lr: 0.0001
        weight_decay: 0.00001
    scheduler: CosineAnnealingLR
    scheduler_params:
        T_max: 8
        eta_min: 0.000001
        verbose: True
    epochs: *epoch  

progressive_train_params:  
    loss:
        balanceBCE:
            beta: 0.99
    epoch:  2
    log_interval: 10
    batch_size: 64
    early_stopping: True
    patient: 3

mini_data:
    train: -1
    test: -1

progressive_mini_data:
    train: 200
    val: 200


    


